from .workspace import (
    ComplaintWorkspaceService,
    DEFAULT_CLAIM_ELEMENTS,
    DEFAULT_INTAKE_QUESTIONS,
    build_mediator_prompt,
    get_complaint_readiness,
    get_ui_readiness,
    get_client_release_gate,
    get_tooling_contract,
    get_workspace_data_schema,
    search_workspace_dataset,
    create_identity,
    export_complaint_packet,
    export_complaint_markdown,
    export_complaint_pdf,
    export_complaint_docx,
    analyze_complaint_output,
    execute_packaged_docket_proof_revalidation_queue,
    persist_packaged_docket_proof_revalidation_queue,
    get_docket_dataset_graph,
    get_docket_dataset_metadata,
    get_formal_diagnostics,
    get_filing_provenance,
    get_packaged_docket_operator_dashboard,
    get_provider_diagnostics,
    review_generated_exports,
    update_claim_type,
    generate_decentralized_id,
    generate_complaint,
    get_workflow_capabilities,
    migrate_legacy_workspace_data,
    import_gmail_evidence,
    import_local_evidence,
    load_packaged_docket_operator_dashboard_report,
    list_claim_elements,
    list_intake_questions,
    list_mcp_tools,
    optimize_ui,
    reset_session,
    review_ui,
    review_case,
    run_intake_chat_turn,
    run_gmail_duckdb_pipeline,
    run_browser_audit,
    save_evidence,
    search_docket_dataset,
    search_email_duckdb_corpus,
    start_session,
    submit_intake_answers,
    update_case_synopsis,
    update_draft,
    view_docket_dataset,
)

__all__ = [
    "ComplaintWorkspaceService",
    "DEFAULT_CLAIM_ELEMENTS",
    "DEFAULT_INTAKE_QUESTIONS",
    "attach_complaint_workspace_routes",
    "build_mediator_prompt",
    "get_complaint_readiness",
    "get_ui_readiness",
    "get_client_release_gate",
    "get_tooling_contract",
    "get_workspace_data_schema",
    "search_workspace_dataset",
    "build_ui_ux_review_prompt",
    "collect_screenshot_artifacts",
    "complaint_cli_main",
    "complaint_generator_main",
    "complaint_mcp_server_main",
    "complaint_workspace_cli_app",
    "complaint_workspace_cli_main",
    "create_identity",
    "create_complaint_workspace_router",
    "create_review_dashboard_app",
    "create_review_surface_app",
    "create_ui_review_report",
    "analyze_complaint_output",
    "execute_packaged_docket_proof_revalidation_queue",
    "persist_packaged_docket_proof_revalidation_queue",
    "get_docket_dataset_graph",
    "get_docket_dataset_metadata",
    "get_formal_diagnostics",
    "get_filing_provenance",
    "get_packaged_docket_operator_dashboard",
    "get_provider_diagnostics",
    "review_generated_exports",
    "run_main",
    "export_complaint_packet",
    "export_complaint_markdown",
    "export_complaint_pdf",
    "export_complaint_docx",
    "generate_decentralized_id",
    "generate_complaint",
    "get_workflow_capabilities",
    "migrate_legacy_workspace_data",
    "handle_jsonrpc_message",
    "import_gmail_evidence",
    "import_local_evidence",
    "load_packaged_docket_operator_dashboard_report",
    "list_claim_elements",
    "list_intake_questions",
    "list_mcp_tools",
    "optimize_ui",
    "reset_session",
    "review_screenshot_audit_with_llm_router",
    "review_ui",
    "review_case",
    "run_intake_chat_turn",
    "run_gmail_duckdb_pipeline",
    "run_browser_audit",
    "run_end_to_end_complaint_browser_audit",
    "run_closed_loop_ui_ux_improvement",
    "run_iterative_ui_ux_workflow",
    "run_playwright_screenshot_audit",
    "run_ui_review_workflow",
    "structure_ui_ux_review",
    "ui_optimizer_daemon_main",
    "ui_optimizer_daemon_build_parser",
    "ui_optimizer_daemon_run",
    "ui_optimizer_daemon_start",
    "ui_optimizer_daemon_status",
    "ui_optimizer_daemon_stop",
    "save_evidence",
    "search_docket_dataset",
    "search_email_duckdb_corpus",
    "start_session",
    "submit_intake_answers",
    "tool_list_payload",
    "update_claim_type",
    "update_case_synopsis",
    "update_draft",
    "view_docket_dataset",
]

__version__ = "0.1.0"

_LAZY_EXPORTS = {
    "attach_complaint_workspace_routes": (".apps", "attach_complaint_workspace_routes"),
    "create_complaint_workspace_router": (".apps", "create_complaint_workspace_router"),
    "create_review_dashboard_app": (".apps", "create_review_dashboard_app"),
    "create_review_surface_app": (".apps", "create_review_surface_app"),
    "handle_jsonrpc_message": (".mcp", "handle_jsonrpc_message"),
    "tool_list_payload": (".mcp", "tool_list_payload"),
    "build_ui_ux_review_prompt": (".ui_ux_workflow", "build_ui_ux_review_prompt"),
    "collect_screenshot_artifacts": (".ui_ux_workflow", "collect_screenshot_artifacts"),
    "review_screenshot_audit_with_llm_router": (".ui_ux_workflow", "review_screenshot_audit_with_llm_router"),
    "run_end_to_end_complaint_browser_audit": (".ui_ux_workflow", "run_end_to_end_complaint_browser_audit"),
    "run_closed_loop_ui_ux_improvement": (".ui_ux_workflow", "run_closed_loop_ui_ux_improvement"),
    "run_iterative_ui_ux_workflow": (".ui_ux_workflow", "run_iterative_ui_ux_workflow"),
    "run_playwright_screenshot_audit": (".ui_ux_workflow", "run_playwright_screenshot_audit"),
    "structure_ui_ux_review": (".ui_ux_workflow", "structure_ui_ux_review"),
    "ui_optimizer_daemon_build_parser": (".ui_optimizer_daemon", "build_parser"),
    "ui_optimizer_daemon_main": (".ui_optimizer_daemon", "main"),
    "ui_optimizer_daemon_run": (".ui_optimizer_daemon", "_run_daemon"),
    "ui_optimizer_daemon_start": (".ui_optimizer_daemon", "_start_daemon"),
    "ui_optimizer_daemon_status": (".ui_optimizer_daemon", "_status_payload"),
    "ui_optimizer_daemon_stop": (".ui_optimizer_daemon", "_stop_daemon"),
    "create_ui_review_report": ("applications.ui_review", "create_ui_review_report"),
    "run_ui_review_workflow": ("applications.ui_review", "run_ui_review_workflow"),
    "complaint_workspace_cli_app": (".cli", "app"),
    "complaint_cli_main": (".cli", "main"),
    "complaint_workspace_cli_main": (".cli", "main"),
    "complaint_mcp_server_main": (".mcp_server", "main"),
    "complaint_generator_main": (".entrypoints", "main"),
    "run_main": (".entrypoints", "run_main"),
}


def __getattr__(name: str):
    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute_name = target
    if module_name.startswith("."):
        module = __import__(f"{__name__}{module_name}", fromlist=[attribute_name])
    else:
        module = __import__(module_name, fromlist=[attribute_name])
    value = getattr(module, attribute_name)
    globals()[name] = value
    return value
